FROM rogiel/cpp-build:latest
RUN env DEBIAN_FRONTEND=noninteractive apt-get update && env DEBIAN_FRONTEND=noninteractive apt-get install -y \
    xorg-dev \
    libgl-dev \
    libopenal-dev \
    libvulkan-dev \
    mono-devel

